'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("DesBNDBuild.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to /chr/c0000.anibnd.dcx
        '''/chr/c0000.chrbnd.dcx
        '''/chr/c0000.esd.dcx
        '''/chr/c0000_a00_hi.anibnd.dcx
        '''/chr/c0000_a00_lo.anibnd.dcx
        '''/chr/c0000_a00_md.anibnd.dcx
        '''/chr/c0000_a0x.anibnd.dcx
        '''/chr/c0000_a1x.anibnd.dcx
        '''/chr/c0000_a2x.anibnd.dcx
        '''/chr/c0000_a3x.anibnd.dcx
        '''/chr/c0000_a4x.anibnd.dcx
        '''/chr/c0000_a5x.anibnd.dcx
        '''/chr/c0000_a6x.anibnd.dcx
        '''/chr/c0000_a7x.anibnd.dcx
        '''/chr/c0000_a8x.anibnd.dcx
        '''/chr/c0000_a9x.anibnd.dcx
        '''/chr/c0000_c2060.anibnd.dcx
        '''/chr/c0000_c2290.anibnd.dcx
        '''/chr/c0000_c2300.anibnd.dcx
        '''/chr/c0000_c2310.a [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property fileidx() As String
            Get
                Return ResourceManager.GetString("fileidx", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to /action/eventnameid.txt
        '''/action/script/c0000.hks
        '''/action/script/c0001.hks
        '''/action/script/c0002.hks
        '''/action/script/c0004.hks
        '''/action/script/c0006.hks
        '''/action/script/c0100.hks
        '''/action/script/c1030.hks
        '''/action/script/c1040.hks
        '''/action/script/c1041.hks
        '''/action/script/c1050.hks
        '''/action/script/c1060.hks
        '''/action/script/c1070.hks
        '''/action/script/c1090.hks
        '''/action/script/c1100.hks
        '''/action/script/c1105.hks
        '''/action/script/c1110.hks
        '''/action/script/c1120.hks
        '''/action/script/c1130.hks
        '''/action/script/c1131.hks
        '''/action/scrip [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property fileidx_ds3() As String
            Get
                Return ResourceManager.GetString("fileidx_ds3", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
